#!/usr/bin/env python3
"""
AIMC Framework - Organic Growth Visualization
Design Philosophy: Cognitive Growth Tree Metaphor (T-Score ≈ 0.25)

The tree metaphor represents:
- Roots (L1): AI-Assisted Metacognition - foundation, nutrient absorption
- Trunk (L2): Meta-AI Awareness - connection, stability, growth conduit
- Canopy/Fruits (L3): Independent Metacognition - fruition, transferable skills

Academic Justification:
- Tree of Knowledge metaphor in educational philosophy
- Organic growth parallels Piaget's developmental stages
- Root-to-fruit progression mirrors internalization process

Author: Generated by 21-Conceptual-Framework-Visualizer (Research Coordinator v3.1)
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.patches import FancyBboxPatch, Circle, Polygon, PathPatch
from matplotlib.path import Path
from matplotlib.colors import LinearSegmentedColormap
import matplotlib.patheffects as path_effects
import os

# ============================================================================
# COLOR PALETTE - Academic Modern with Organic Tones
# ============================================================================

COLORS = {
    # Background
    'bg_primary': '#FAFBF9',
    'bg_secondary': '#F0F4EC',

    # Level 3 - Canopy/Fruits (Golden Harvest)
    'l3_primary': '#D4A84B',      # Rich gold
    'l3_secondary': '#E8C872',    # Light gold
    'l3_accent': '#8B6914',       # Dark gold
    'l3_text': '#5C4A0F',

    # Level 2 - Branches/Leaves (Forest Green)
    'l2_primary': '#2D5A3D',      # Deep forest
    'l2_secondary': '#4A8B5C',    # Medium green
    'l2_accent': '#6AAF7B',       # Light green
    'l2_text': '#1A3825',

    # Level 1 - Trunk (Warm Wood)
    'l1_primary': '#6B4423',      # Rich brown
    'l1_secondary': '#8B6240',    # Medium brown
    'l1_accent': '#A67B5B',       # Light brown
    'l1_text': '#3D2514',

    # Foundation - Roots (Earth)
    'root_primary': '#4A3728',    # Dark earth
    'root_secondary': '#6B5344',  # Medium earth
    'root_line': '#8B7355',

    # Text and UI
    'text_primary': '#1F2937',
    'text_secondary': '#4B5563',
    'text_light': '#9CA3AF',
    'white': '#FFFFFF',

    # Arrows and connections
    'arrow': '#6B7280',
    'glow': '#D4A84B33',
}

# ============================================================================
# CONFIGURATION
# ============================================================================

WIDTH = 16
HEIGHT = 12
DPI = 300
OUTPUT_DIR = os.path.dirname(os.path.abspath(__file__))

# ============================================================================
# DRAWING FUNCTIONS
# ============================================================================

def draw_organic_blob(ax, center_x, center_y, width, height, color, alpha=1.0,
                      noise_scale=0.15, n_points=100):
    """Draw an organic, blob-like shape using bezier curves."""
    theta = np.linspace(0, 2 * np.pi, n_points)

    # Add organic noise
    np.random.seed(42)  # Reproducible
    noise = 1 + noise_scale * np.sin(3 * theta) * np.cos(5 * theta + 0.5)

    # Ellipse base with noise
    x = center_x + (width / 2) * np.cos(theta) * noise
    y = center_y + (height / 2) * np.sin(theta) * noise

    ax.fill(x, y, color=color, alpha=alpha, zorder=2)
    return x, y


def draw_tree_trunk(ax, base_x, base_y, top_x, top_y, base_width, top_width, color):
    """Draw an organic tree trunk with slight curve."""
    # Create trunk vertices with organic curve
    n_points = 50
    t = np.linspace(0, 1, n_points)

    # Slight S-curve for organic feel
    curve_offset = 0.3 * np.sin(t * np.pi)

    # Width taper
    width = base_width + (top_width - base_width) * t

    # Center line
    center_x = base_x + (top_x - base_x) * t + curve_offset
    center_y = base_y + (top_y - base_y) * t

    # Left and right edges
    left_x = center_x - width / 2
    right_x = center_x + width / 2

    # Create polygon vertices
    vertices = list(zip(left_x, center_y)) + list(zip(right_x[::-1], center_y[::-1]))
    trunk = Polygon(vertices, closed=True, facecolor=color, edgecolor=COLORS['l1_accent'],
                   linewidth=2, zorder=3)
    ax.add_patch(trunk)

    # Add bark texture lines
    for i in range(5):
        t_pos = 0.15 + i * 0.15
        idx = int(t_pos * n_points)
        if idx < n_points:
            line_y = center_y[idx]
            line_x = center_x[idx]
            line_w = width[idx] * 0.6
            ax.plot([line_x - line_w/2, line_x + line_w/2], [line_y, line_y],
                   color=COLORS['l1_accent'], linewidth=1.5, alpha=0.5, zorder=4)


def draw_roots(ax, base_x, base_y, spread, depth, color):
    """Draw organic root system."""
    np.random.seed(123)

    # Main roots
    n_roots = 5
    for i in range(n_roots):
        angle = np.pi + (i - n_roots//2) * 0.4  # Spread downward
        length = depth * (0.7 + 0.3 * np.random.random())

        # Root path with organic curve
        t = np.linspace(0, 1, 30)
        wobble = 0.2 * np.sin(t * 3 * np.pi) * (1 - t)  # Decreasing wobble

        end_x = base_x + spread * np.cos(angle) * (0.5 + 0.5 * np.abs(i - n_roots//2) / (n_roots//2))
        end_y = base_y - length

        root_x = base_x + (end_x - base_x) * t + wobble
        root_y = base_y + (end_y - base_y) * t

        # Taper width
        widths = 8 * (1 - t * 0.8)

        ax.plot(root_x, root_y, color=color, linewidth=widths[0], solid_capstyle='round', zorder=1)

        # Small root branches
        for j in range(2):
            branch_t = 0.4 + j * 0.3
            idx = int(branch_t * len(t))
            branch_angle = angle + (np.random.random() - 0.5) * 0.8
            branch_len = length * 0.3 * np.random.random()

            bx = [root_x[idx], root_x[idx] + branch_len * np.cos(branch_angle) * 0.5]
            by = [root_y[idx], root_y[idx] - branch_len * 0.3]
            ax.plot(bx, by, color=color, linewidth=3, solid_capstyle='round', zorder=1)


def draw_canopy(ax, center_x, center_y, width, height, colors):
    """Draw organic tree canopy with layered leaves."""
    # Multiple overlapping organic shapes for depth
    layers = [
        (0, 0, 1.0, 1.0, colors[0], 0.9),
        (-0.3, 0.2, 0.8, 0.85, colors[1], 0.8),
        (0.35, 0.15, 0.75, 0.8, colors[1], 0.8),
        (0, 0.35, 0.6, 0.65, colors[2], 0.85),
    ]

    for dx, dy, w_scale, h_scale, color, alpha in layers:
        draw_organic_blob(ax, center_x + dx, center_y + dy,
                         width * w_scale, height * h_scale,
                         color, alpha, noise_scale=0.12)


def draw_fruits(ax, positions, color, glow_color):
    """Draw golden fruits representing achieved metacognition."""
    for x, y, size in positions:
        # Glow effect
        glow = Circle((x, y), size * 1.8, color=glow_color, alpha=0.3, zorder=5)
        ax.add_patch(glow)

        # Main fruit
        fruit = Circle((x, y), size, color=color, zorder=6)
        ax.add_patch(fruit)

        # Highlight
        highlight = Circle((x - size*0.3, y + size*0.3), size * 0.25,
                          color=COLORS['white'], alpha=0.6, zorder=7)
        ax.add_patch(highlight)


def draw_level_label(ax, x, y, level_num, title, subtitle, color, text_color,
                     bg_alpha=0.9, fontsize_title=14, fontsize_sub=10):
    """Draw a level label with organic background."""
    # Background blob
    bbox = FancyBboxPatch((x - 2.2, y - 0.5), 4.4, 1.2,
                          boxstyle="round,pad=0.1,rounding_size=0.3",
                          facecolor=color, alpha=bg_alpha,
                          edgecolor=text_color, linewidth=2, zorder=10)
    ax.add_patch(bbox)

    # Level badge
    badge = Circle((x - 1.8, y + 0.1), 0.35, color=text_color, zorder=11)
    ax.add_patch(badge)
    ax.text(x - 1.8, y + 0.1, f'L{level_num}', fontsize=11, fontweight='bold',
            ha='center', va='center', color=COLORS['white'], zorder=12)

    # Title
    ax.text(x + 0.3, y + 0.3, title, fontsize=fontsize_title, fontweight='bold',
            ha='center', va='center', color=text_color, zorder=11)

    # Subtitle
    ax.text(x + 0.3, y - 0.15, subtitle, fontsize=fontsize_sub, fontstyle='italic',
            ha='center', va='center', color=text_color, alpha=0.8, zorder=11)


def draw_arrow_organic(ax, start, end, label, color):
    """Draw organic curved arrow with label."""
    x1, y1 = start
    x2, y2 = end

    # Curved path
    mid_x = (x1 + x2) / 2 + 0.5
    mid_y = (y1 + y2) / 2

    ax.annotate('', xy=(x2, y2), xytext=(x1, y1),
                arrowprops=dict(arrowstyle='->', color=color, lw=2,
                               connectionstyle='arc3,rad=0.2'))

    # Label
    ax.text(mid_x + 0.3, mid_y, label, fontsize=10, fontstyle='italic',
            ha='left', va='center', color=color,
            bbox=dict(boxstyle='round,pad=0.3', facecolor=COLORS['bg_primary'],
                     edgecolor='none', alpha=0.8))


def draw_info_box(ax, x, y, width, height, items, title, color, title_color):
    """Draw information box with organic styling."""
    # Background
    box = FancyBboxPatch((x, y), width, height,
                         boxstyle="round,pad=0.02,rounding_size=0.15",
                         facecolor=color, alpha=0.95,
                         edgecolor=title_color, linewidth=2, zorder=10)
    ax.add_patch(box)

    # Title
    ax.text(x + width/2, y + height - 0.25, title, fontsize=11, fontweight='bold',
            ha='center', va='center', color=title_color, zorder=11)

    # Items
    for i, item in enumerate(items):
        ax.text(x + 0.15, y + height - 0.6 - i * 0.35, f'• {item}',
                fontsize=9, ha='left', va='center', color=COLORS['text_primary'], zorder=11)


# ============================================================================
# MAIN VISUALIZATION
# ============================================================================

def create_aimc_organic():
    """Create the organic AIMC Framework visualization."""

    fig, ax = plt.subplots(figsize=(WIDTH, HEIGHT), dpi=DPI)

    # Background gradient effect
    gradient = np.linspace(0, 1, 256).reshape(1, -1)
    gradient = np.vstack((gradient, gradient))

    ax.imshow(gradient, aspect='auto', cmap=LinearSegmentedColormap.from_list(
        'bg', [COLORS['bg_secondary'], COLORS['bg_primary']]),
              extent=[0, WIDTH, 0, HEIGHT], zorder=0, alpha=0.5)

    ax.set_xlim(0, WIDTH)
    ax.set_ylim(0, HEIGHT)
    ax.set_aspect('equal')
    ax.axis('off')

    # ========================================
    # HEADER
    # ========================================

    ax.text(WIDTH/2, HEIGHT - 0.6,
            'AI-Integrated Metacognition (AIMC) Framework',
            fontsize=22, fontweight='bold', ha='center', va='top',
            color=COLORS['text_primary'])

    ax.text(WIDTH/2, HEIGHT - 1.1,
            'Cognitive Growth Model: From AI-Assisted Roots to Independent Fruition',
            fontsize=12, fontstyle='italic', ha='center', va='top',
            color=COLORS['text_secondary'])

    # ========================================
    # TREE STRUCTURE
    # ========================================

    tree_base_x = WIDTH / 2
    tree_base_y = 2.5

    # === ROOTS (Foundation) ===
    draw_roots(ax, tree_base_x, tree_base_y - 0.5, spread=3.5, depth=1.8,
               color=COLORS['root_primary'])

    # Root zone label
    ax.text(tree_base_x, 0.8, '🌱 Foundation: AI Tools & Environment',
            fontsize=10, ha='center', va='center', color=COLORS['root_secondary'],
            fontstyle='italic')

    # === TRUNK (Level 1: AI-Assisted Metacognition) ===
    trunk_top_y = 5.5
    draw_tree_trunk(ax, tree_base_x, tree_base_y, tree_base_x, trunk_top_y,
                   base_width=1.8, top_width=1.2, color=COLORS['l1_primary'])

    # Level 1 info boxes on trunk
    l1_items = ['Prompt Engineering', 'Output Evaluation', 'Iterative Refinement']
    for i, item in enumerate(l1_items):
        y_pos = tree_base_y + 0.8 + i * 0.9
        ax.text(tree_base_x, y_pos, item, fontsize=9, ha='center', va='center',
                color=COLORS['white'], fontweight='bold', zorder=5,
                bbox=dict(boxstyle='round,pad=0.2', facecolor=COLORS['l1_secondary'],
                         edgecolor='none', alpha=0.9))

    # === BRANCHES (Level 2: Meta-AI Awareness) ===
    branch_y = trunk_top_y + 0.5

    # Left branch
    ax.annotate('', xy=(tree_base_x - 2.5, branch_y + 1.5),
                xytext=(tree_base_x - 0.3, trunk_top_y),
                arrowprops=dict(arrowstyle='-', color=COLORS['l2_primary'], lw=15,
                               connectionstyle='arc3,rad=0.3'))

    # Right branch
    ax.annotate('', xy=(tree_base_x + 2.5, branch_y + 1.5),
                xytext=(tree_base_x + 0.3, trunk_top_y),
                arrowprops=dict(arrowstyle='-', color=COLORS['l2_primary'], lw=15,
                               connectionstyle='arc3,rad=-0.3'))

    # Central growth
    ax.annotate('', xy=(tree_base_x, branch_y + 2.5),
                xytext=(tree_base_x, trunk_top_y),
                arrowprops=dict(arrowstyle='-', color=COLORS['l2_primary'], lw=12))

    # Level 2 leaf clusters
    leaf_positions = [
        (tree_base_x - 2.8, branch_y + 2, 1.8, 1.4),
        (tree_base_x + 2.8, branch_y + 2, 1.8, 1.4),
        (tree_base_x, branch_y + 3, 2.2, 1.6),
    ]

    l2_items = ['Understanding AI\nCapabilities', 'Evaluating AI\nReliability',
                'Knowing When\nto Use AI']

    for i, (lx, ly, lw, lh) in enumerate(leaf_positions):
        draw_organic_blob(ax, lx, ly, lw, lh, COLORS['l2_secondary'], alpha=0.85)
        ax.text(lx, ly, l2_items[i], fontsize=8, ha='center', va='center',
                color=COLORS['white'], fontweight='bold', zorder=6)

    # === CANOPY (Level 3: Independent Metacognition) ===
    canopy_y = branch_y + 4.5
    draw_canopy(ax, tree_base_x, canopy_y, 6, 3.5,
               [COLORS['l3_secondary'], COLORS['l3_primary'], COLORS['l3_accent']])

    # Fruits (achievements)
    fruit_positions = [
        (tree_base_x - 1.5, canopy_y + 0.8, 0.35),
        (tree_base_x + 1.2, canopy_y + 0.5, 0.4),
        (tree_base_x - 0.3, canopy_y + 1.3, 0.3),
        (tree_base_x + 1.8, canopy_y + 1.0, 0.28),
        (tree_base_x - 1.0, canopy_y + 0.2, 0.32),
    ]
    draw_fruits(ax, fruit_positions, COLORS['l3_primary'], COLORS['glow'])

    # Level 3 labels in canopy
    l3_items = ['Self-Regulated\nLearning', 'Internalized\nMonitoring',
                'Transfer to\nNovel Contexts']
    l3_positions = [(tree_base_x - 1.8, canopy_y - 0.3),
                    (tree_base_x + 1.8, canopy_y - 0.3),
                    (tree_base_x, canopy_y + 0.8)]

    for (x, y), item in zip(l3_positions, l3_items):
        ax.text(x, y, item, fontsize=8, ha='center', va='center',
                color=COLORS['l3_text'], fontweight='bold', zorder=8)

    # ========================================
    # LEVEL LABELS (Right side)
    # ========================================

    label_x = WIDTH - 3.5

    draw_level_label(ax, label_x, canopy_y, 3, 'Independent Metacognition',
                    'Without-AI Transfer', COLORS['l3_secondary'], COLORS['l3_text'])

    draw_level_label(ax, label_x, branch_y + 1.5, 2, 'Meta-AI Awareness',
                    'About-AI Knowledge', COLORS['l2_accent'], COLORS['l2_text'])

    draw_level_label(ax, label_x, tree_base_y + 1.5, 1, 'AI-Assisted Metacognition',
                    'With-AI Context', COLORS['l1_accent'], COLORS['l1_text'])

    # ========================================
    # TRANSITION ARROWS
    # ========================================

    draw_arrow_organic(ax, (label_x - 2, tree_base_y + 2.2), (label_x - 2, branch_y + 0.8),
                      'Reflection', COLORS['arrow'])

    draw_arrow_organic(ax, (label_x - 2, branch_y + 2.2), (label_x - 2, canopy_y - 0.8),
                      'Internalization', COLORS['arrow'])

    # ========================================
    # KEY FINDING BOX
    # ========================================

    warning_x = 0.8
    warning_y = 1.5

    warning_box = FancyBboxPatch((warning_x, warning_y), 5.5, 2.2,
                                  boxstyle="round,pad=0.02,rounding_size=0.2",
                                  facecolor='#FEF3C7', alpha=0.95,
                                  edgecolor='#D97706', linewidth=2, zorder=10)
    ax.add_patch(warning_box)

    ax.text(warning_x + 0.3, warning_y + 1.9, '⚠️ Key Finding',
            fontsize=11, fontweight='bold', color='#92400E', zorder=11)

    warning_text = ('Current evidence primarily assesses L1.\n'
                   'The Cognitive Dependency Hypothesis\n'
                   'predicts divergent effects at L3\n'
                   '(independent, transferable metacognition).')
    ax.text(warning_x + 0.3, warning_y + 0.9, warning_text,
            fontsize=9, color='#78350F', zorder=11, linespacing=1.4)

    # ========================================
    # LEGEND
    # ========================================

    legend_x = 0.8
    legend_y = 4.5

    legend_items = [
        ('🍎', 'Fruits = Achieved metacognitive independence'),
        ('🌿', 'Canopy = Transfer-ready knowledge'),
        ('🪵', 'Trunk = AI-assisted skill building'),
        ('🌱', 'Roots = AI tools foundation'),
    ]

    ax.text(legend_x, legend_y + 1.3, 'Growth Metaphor', fontsize=10, fontweight='bold',
            color=COLORS['text_primary'])

    for i, (icon, text) in enumerate(legend_items):
        ax.text(legend_x, legend_y + 0.9 - i * 0.35, f'{icon} {text}',
                fontsize=8, color=COLORS['text_secondary'])

    # ========================================
    # CITATION
    # ========================================

    ax.text(WIDTH/2, 0.3,
            'You, H. (2026). Generative AI in Higher Education: A Three-Level Meta-Analysis. '
            'Pennsylvania State University',
            fontsize=8, ha='center', va='center', color=COLORS['text_light'],
            fontstyle='italic')

    # ========================================
    # SAVE OUTPUTS
    # ========================================

    plt.tight_layout(pad=0.5)

    # PNG
    png_path = os.path.join(OUTPUT_DIR, 'AIMC_Framework_Organic.png')
    plt.savefig(png_path, dpi=DPI, bbox_inches='tight', facecolor=COLORS['bg_primary'])
    print(f'✅ Saved PNG: {png_path}')

    # PDF
    pdf_path = os.path.join(OUTPUT_DIR, 'AIMC_Framework_Organic.pdf')
    plt.savefig(pdf_path, format='pdf', bbox_inches='tight', facecolor=COLORS['bg_primary'])
    print(f'✅ Saved PDF: {pdf_path}')

    # SVG
    svg_path = os.path.join(OUTPUT_DIR, 'AIMC_Framework_Organic.svg')
    plt.savefig(svg_path, format='svg', bbox_inches='tight', facecolor=COLORS['bg_primary'])
    print(f'✅ Saved SVG: {svg_path}')

    plt.close()

    return png_path


if __name__ == '__main__':
    create_aimc_organic()
